name: CI Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Packages
        run: |
          npm i -g corepack@latest
          corepack enable
          pnpm install

      - name: Build Code
        run: |
          pnpm run build
          pnpm run test
          pnpm biome ci src
