name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Packages
        run: |
          npm i -g corepack@latest
          corepack enable
          pnpm install

      - name: Build and Package
        run: |
          pnpm run build
          pnpm run sync
          pnpm run zip
          pnpm run test
          pnpm biome ci src

      - name: Deploy to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: apps
          extra_args: "--destination-path standup-roulette"
          connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
          overwrite: "true"

      - name: Deploy to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/index.user.js
            standup-roulette-extension-v*.zip
