name: Release (Azure)

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install Packages
        run: |
          npm i -g corepack@latest
          corepack enable
          pnpm install

      - name: Build Code
        run: |
          pnpm run build
          pnpm run test
          pnpm biome ci src

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Release
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: apps
          extra_args: "--destination-path standup-roulette"
          connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
          overwrite: "true"
